package com.frozenheart.backend.core.constant;

import org.springframework.http.HttpStatus;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

// Sau này nên tạo i18n để hỗ trợ đa ngôn ngữ, thay vào trường message
@Getter
@NoArgsConstructor
@AllArgsConstructor
public enum ResponseCode {
    SUCCESS("1000", "SUCCESS", HttpStatus.OK),
    DATABASE_CONNECTION_ERROR("1001", "DATABASE_CONNECTION_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    MISSING_REQUIRED_PARAMETER("1002", "MISSING_REQUIRED_PARAMETER", HttpStatus.BAD_REQUEST),
    INVALID_PARAMETER_TYPE("1003", "INVALID_PARAMETER_TYPE", HttpStatus.BAD_REQUEST),

    // 1004 quá chung chung, thông báo không thân thiện với người dùng
    INVALID_PARAMETER_VALUE("1004", "INVALID_PARAMETER_VALUE", HttpStatus.BAD_REQUEST),

    UNKNOWN_SYSTEM_ERROR("1005", "UNKNOWN_SYSTEM_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),
    FILE_SIZE_EXCEEDED("1006", "FILE_SIZE_EXCEEDED", HttpStatus.CONTENT_TOO_LARGE),
    FILE_UPLOAD_FAILED("1007", "FILE_UPLOAD_FAILED", HttpStatus.INTERNAL_SERVER_ERROR),
    MEDIA_LIMIT_EXCEEDED("1008", "MEDIA_LIMIT_EXCEEDED", HttpStatus.BAD_REQUEST),
    ACCESS_DENIED("1009", "ACCESS_DENIED", HttpStatus.FORBIDDEN),
    ACTION_ALREADY_PERFORMED("1010", "ACTION_ALREADY_PERFORMED", HttpStatus.CONFLICT),
    CONTENT_VIOLATES_POLICY("1011", "CONTENT_VIOLATES_POLICY", HttpStatus.FORBIDDEN),
    RESOURCE_NOT_FOUND("1012", "RESOURCE_NOT_FOUND", HttpStatus.NOT_FOUND),

    DEVICE_NOT_FOUND("9989", "DEVICE_NOT_FOUND", HttpStatus.NOT_FOUND),
    INCORRECT_IDENTIFIER("9990", "INCORRECT_IDENTIFIER", HttpStatus.BAD_REQUEST),
    ACCOUNT_NOT_ACTIVE("9991", "ACCOUNT_NOT_ACTIVE", HttpStatus.FORBIDDEN),
    USER_NOT_VERIFIED("9992", "USER_NOT_VERIFIED", HttpStatus.FORBIDDEN),
    VERIFICATION_CODE_INVALID("9993", "VERIFICATION_CODE_INVALID", HttpStatus.BAD_REQUEST),
    NO_MORE_DATA("9994", "NO_MORE_DATA", HttpStatus.OK),
    USER_NOT_FOUND("9995", "USER_NOT_FOUND", HttpStatus.NOT_FOUND),
    USER_ALREADY_EXISTS("9996", "USER_ALREADY_EXISTS", HttpStatus.CONFLICT),
    METHOD_NOT_ALLOWED("9997", "METHOD_NOT_ALLOWED", HttpStatus.METHOD_NOT_ALLOWED),
    TOKEN_INVALID_OR_EXPIRED("9998", "TOKEN_INVALID_OR_EXPIRED", HttpStatus.UNAUTHORIZED),
    UNHANDLED_EXCEPTION("9999", "UNHANDLED_EXCEPTION", HttpStatus.INTERNAL_SERVER_ERROR),

    QUESTION_NOT_FOUND("2001", "QUESTION_NOT_FOUND", HttpStatus.NOT_FOUND),
    QUESTION_ALREADY_REVIEWED("2002", "QUESTION_ALREADY_REVIEWED", HttpStatus.CONFLICT),
    DUPLICATE_QUESTION_DETECTED("2003", "DUPLICATE_QUESTION_DETECTED", HttpStatus.CONFLICT),
    INVALID_QUESTION_FORMAT("2004", "INVALID_QUESTION_FORMAT", HttpStatus.BAD_REQUEST),

    // Quyết định thiết kế đã không còn sử dụng phương án này
    FILE_CONTAINS_MALWARE("2005", "FILE_CONTAINS_MALWARE", HttpStatus.BAD_REQUEST),

    REVIEW_PERMISSION_DENIED("2006", "REVIEW_PERMISSION_DENIED", HttpStatus.FORBIDDEN),
    QUESTION_HIDDEN_BY_AUTHOR("2007", "QUESTION_HIDDEN_BY_AUTHOR", HttpStatus.FORBIDDEN),
    SESSION_NOT_FOUND("2008", "SESSION_NOT_FOUND", HttpStatus.NOT_FOUND),
    POST_NOT_FOUND("2009", "POST_NOT_FOUND", HttpStatus.NOT_FOUND),
    STALE_DATA_DETECTED("2010", "STALE_DATA_DETECTED", HttpStatus.PRECONDITION_FAILED),

    AI_SERVICE_UNAVAILABLE("2101", "AI_SERVICE_UNAVAILABLE", HttpStatus.SERVICE_UNAVAILABLE),
    AI_RESPONSE_FORMAT_INVALID("2102", "AI_RESPONSE_FORMAT_INVALID", HttpStatus.BAD_GATEWAY),
    HALLUCINATION_DETECTED("2103", "HALLUCINATION_DETECTED", HttpStatus.UNPROCESSABLE_CONTENT),
    AI_IMAGE_MODIFICATION_NOT_SUPPORTED("2104", "AI_IMAGE_MODIFICATION_NOT_SUPPORTED", HttpStatus.BAD_REQUEST),
    AI_RATE_LIMIT_EXCEEDED("2105", "AI_RATE_LIMIT_EXCEEDED", HttpStatus.TOO_MANY_REQUESTS),

    PREDICTION_ALREADY_PLACED("2201", "PREDICTION_ALREADY_PLACED", HttpStatus.CONFLICT),
    PREDICTION_WINDOW_CLOSED("2202", "PREDICTION_WINDOW_CLOSED", HttpStatus.CONFLICT),
    INVALID_PREDICTION_TARGET("2203", "INVALID_PREDICTION_TARGET", HttpStatus.BAD_REQUEST),
    LEADERBOARD_PERIOD_INVALID("2204", "LEADERBOARD_PERIOD_INVALID", HttpStatus.BAD_REQUEST),

    ALREADY_FRIENDS("2301", "ALREADY_FRIENDS", HttpStatus.CONFLICT),
    FRIEND_REQUEST_PENDING("2302", "FRIEND_REQUEST_PENDING", HttpStatus.CONFLICT),
    INVALID_FRIENDSHIP_STATUS("2303", "INVALID_FRIENDSHIP_STATUS", HttpStatus.BAD_REQUEST),
    CANNOT_INTERACT_WITH_SELF("2304", "CANNOT_INTERACT_WITH_SELF", HttpStatus.BAD_REQUEST),
    USER_IS_BLOCKED("2305", "USER_IS_BLOCKED", HttpStatus.FORBIDDEN),
    CONVERSATION_RESTRICTED("2306", "CONVERSATION_RESTRICTED", HttpStatus.FORBIDDEN),
    REPORT_TARGET_NOT_FOUND("2307", "REPORT_TARGET_NOT_FOUND", HttpStatus.NOT_FOUND),
    NOT_FOLLOWING("2308", "NOT_FOLLOWING", HttpStatus.CONFLICT),
    ALREADY_FOLLOWING("2309", "ALREADY_FOLLOWING", HttpStatus.CONFLICT),
    ALREADY_BLOCKED("2310", "ALREADY_BLOCKED", HttpStatus.CONFLICT),
    NOT_BLOCKED("2311", "NOT_BLOCKED", HttpStatus.CONFLICT),

    MESSAGE_RECALL_TIME_EXPIRED("2401", "MESSAGE_RECALL_TIME_EXPIRED", HttpStatus.CONFLICT),
    PUSH_NOTIFICATION_DISABLED("2402", "PUSH_NOTIFICATION_DISABLED", HttpStatus.FORBIDDEN),
    PUSH_NOTIFICATION_TOKEN_INVALID("2403", "PUSH_NOTIFICATION_TOKEN_INVALID", HttpStatus.BAD_REQUEST),
    CONTENT_TOO_LONG("2404", "CONTENT_TOO_LONG", HttpStatus.BAD_REQUEST),
    CONVERSATION_NOT_FOUND("2405", "CONVERSATION_NOT_FOUND", HttpStatus.NOT_FOUND),
    MESSAGE_NOT_FOUND("2406", "MESSAGE_NOT_FOUND", HttpStatus.NOT_FOUND),
    NOT_MESSAGE_OWNER("2407", "NOT_MESSAGE_OWNER", HttpStatus.FORBIDDEN),
    INVALID_PIN("2408", "INVALID_PIN", HttpStatus.BAD_REQUEST),
    PIN_NOT_SET("2409", "PIN_NOT_SET", HttpStatus.BAD_REQUEST),
    CONSTRAINTS_UNSATISFIED("2410", "CONSTRAINTS_UNSATISFIED", HttpStatus.BAD_REQUEST),

    ACTION_NOT_ALLOWED("2901", "ACTION_NOT_ALLOWED", HttpStatus.FORBIDDEN),

    QUESTION_ALREADY_ANSWERED("2501", "QUESTION_ALREADY_ANSWERED", HttpStatus.CONFLICT),
    CANNOT_RATE_OWN_QUESTION("2502", "CANNOT_RATE_OWN_QUESTION", HttpStatus.BAD_REQUEST),
    INVALID_CONFIDENCE_SCORE("2503", "INVALID_CONFIDENCE_SCORE", HttpStatus.BAD_REQUEST),
    NOT_ENOUGH_QUESTIONS("2601", "NOT_ENOUGH_QUESTIONS", HttpStatus.BAD_REQUEST),

    COSMETIC_NOT_OWNED("2701", "COSMETIC_NOT_OWNED", HttpStatus.FORBIDDEN),
    COSMETIC_EXPIRED("2702", "COSMETIC_EXPIRED", HttpStatus.GONE),

    NOTIFICATION_NOT_FOUND("2801", "NOTIFICATION_NOT_FOUND", HttpStatus.NOT_FOUND)

    ;

    private String code;
    private String message;
    private HttpStatus httpStatus;

}
